# Change these first
owner: somehow22 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: OpenAI
    url: https://api.openai.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nxapi.us.kg
  # baseUrl: /nx
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Magpie Status
  introTitle: "**This** a status page to track my services' availability"
  introMessage: Watch it, Dude!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
